### ISSUE TITLE
FAST cannot find the path for own models

### ISSUE THREAD

**Issue by AleSgueglia** [fast-aircraft-design/FAST-OAD#316] opened 2021-04-19 14:52 UTC
Hello,
I upgraded the code to the v1.0.1 (and now to 1.0.2) but I have an issue about the path of my models. 
Indeed, in the repository where I place my YAML file, I create another repository "models" which contain my weights and performance modules, and then in my YAML file I specify: 

```
module_folders: 
    - /models/weight 
    - /models/performance
```
    
When I use the command fastoad eval, I came out with the following error: 

```
WARNING : SKIPPED C:/models/weight: it does not exist.
WARNING : SKIPPED C:/models/performance: it does not exist.
```

It's like FAST by default is searching the modules under C:\, for the time being I placed my models at the top, but I would like to know if there's a solution in order to have the models in the repository together with the YAML file. 

Best regards, 
Alessandro Sgueglia

**Comment by christophe-david** [comment] 2021-04-19 19:11
Hi,
By putting `/` at the beginning of your paths, you provide absolute paths.
To give relative paths (that will be resolved from location of your configuration file), you can add a `.` or remove the `/`, like below:
```yaml
module_folders: 
    - ./models/weight 
    - models/performance
```

**Comment by AleSgueglia** [comment] 2021-04-19 20:17
Hello,
I already tried this variant too, but I still got the same message unfortunately.

**Comment by christophe-david** [comment] 2021-04-20 07:52
I cannot reproduce anything close to what you describe unless I make the module paths begin by `/`. Providing actual relative paths works in all our tests.
Could you please provide a full example where the problem occurs? (configuration file + module folder tree with possibly simple dummy components + complete screen outputs after run)

**Comment by AleSgueglia** [comment] 2021-04-21 07:10
Attached you will find the whole repository with dummy models and my setup. 
For information, it seems now that I updated to 1.0.2 that if I use `./models/weight` it recognises the path, but I obtain in output the following message: 
`
INFO    : Loading bundles from C:\Users\AlessandroSGUEGLIA\AURA AERO Dropbox\1 - PROGRAMMES\8-MDO_PLATFORM\CODES\OAD_FAST_Dummy\./models/weight
INFO    : Installed bundle weight.mass_breakdown (ID 201 )
INFO    : Installed bundle weight (ID 199 )
INFO    : Loading bundles from C:\Users\AlessandroSGUEGLIA\AURA AERO Dropbox\1 - PROGRAMMES\8-MDO_PLATFORM\CODES\OAD_FAST_Dummy\./models/performance
usage: fastoad [-h] [-v] {gen_conf,gen_inputs,list_modules,list_variables,n2,xdsm,eval,optim,notebooks} ...

FAST-OAD main program

optional arguments:
  -h, --help            show this help message and exit
  -v, --version         shows version number

sub-commands:
  {gen_conf,gen_inputs,list_modules,list_variables,n2,xdsm,eval,optim,notebooks}
    gen_conf            generates a sample configuration file
    gen_inputs          generates the input file
    list_modules        Provides the identifiers of available systems
    list_variables      Lists the variables of the problem
    n2                  Writes the N2 diagram of the problem
    xdsm                Writes the XDSM diagram of the problem
    eval                Runs the analysis
    optim               Runs the optimization
    notebooks           Create ready-to-use notebooks
`
and in the end no evaluation is carrier out. 


[OAD_FAST_Dummy.zip](https://github.com/fast-aircraft-design/FAST-OAD/files/6348763/OAD_FAST_Dummy.zip)

**Comment by christophe-david** [comment] 2021-04-21 13:18
There is a typo in your performance_evaluation.py that creates this error:
```python
@oad.RegisteOpenMDAOSystem("fastoad.performance.hybrid") # <= you miss a 'r' at the end of 'Register'
class Performance(om.ExplicitComponent):
```
I admit that we should better identify such problem and provide a relevant message error (I just created #318 for that, using your test case). 

Nevertheless, once this typo is fixed, the case runs (and fails because of the incorrect optimization definition, and after that, stops at the first iteration, but it runs).

Concerning the initial problem, the management of relative/absolute paths of module folder in 1.0.2 is strictly identical to 1.0.1 (and compared to 1.0.0, 1.0.1 only fixes the error message in case of incorrect path).
Therefore, I really think your problem came only from the unwilling usage of absolute paths in your definition of module folders.

So I close this issue for now. Feel free to reopen it if the problem occurs again.

**Closed by christophe-david** 2021-04-21 13:18 UTC
